Vagrant.configure("2") do |config|
  config.vm.box = "vdelarosa/windows-10"
end
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Dos nodos ubuntu 16.04
    config.vm.define "kali00" do |app|
        app.vm.box = "kalilinux/rolling"
        app.vm.hostname = "kali00"
        app.vm.network  "private_network", ip: "192.168.12.10"
        app.vm.provider "virtualbox" do |v|
            v.memory= 512
            v.cpus = 1
        end
    end
    # Dos nodos ubuntu 16.04
    config.vm.define "nubu01" do |app|
        app.vm.box = "bento/ubuntu-16.04"
        app.vm.hostname = "nubu01"
        app.vm.network  "private_network", ip: "192.168.12.11"
        #app.vm.provision "shell", path: "config-ssh.sh"
        app.vm.provider "virtualbox" do |v|
            v.memory= 512
            v.cpus = 1
        end
    end
    config.vm.define "nubu02" do |app|
        app.vm.box = "bento/ubuntu-16.04"
        app.vm.hostname = "nubu02"
        app.vm.network  "private_network", ip: "192.168.12.12"
        #app.vm.provision "shell", path: "config-ssh.sh"
        app.vm.provider "virtualbox" do |v|
            v.memory= 512
            v.cpus = 1
        end
    end
    config.vm.define "nubu03" do |app|
        app.vm.box = "bento/ubuntu-16.04"
        app.vm.hostname = "nubu03"
        app.vm.network  "private_network", ip: "192.168.12.13"
        #app.vm.provision "shell", path: "config-ssh.sh"
        app.vm.provider "virtualbox" do |v|
            v.memory= 512
            v.cpus = 1
        end
   end
end
